### ISSUE TITLE
Add support for translation keys with dot syntax

### ISSUE THREAD

**Issue by nicodemuz** [psyycker/react-translation#4]
Add support for translation keys with dot syntax. E.g.:
```
{
  "component": {
    "this.is.my.translation.key": "My Value"
  }
}
```

Great library, by the way!!

**Comment by psyycker** [comment]
Hi!

That's a good point, I'll take some time to improve the lib and add this too.
Stay tuned ;)

**Comment by nicodemuz** [comment]
@psyycker any plan to support this? If I were to implement this, where should the logic be implemented?

**Comment by psyycker** [comment]
Hi @nicodemuz very very sorry for the extremely late reply! I've been quite busy with work. If you are still interested in adding this feature, the place you are looking for is https://github.com/psyycker/react-translation/blob/master/src/utils/translation-utils.ts
`getTranslationWithKey` you'd need to change that so that if you are not able to find the key, then try to join it with the next one and keep trying until you are able to move forward (or not!)

**Comment by psyycker** [comment]
This feature has been planned for the version `0.8.0` of the package (see [roadmap](https://trello.com/b/aBwAR0S5/react-translation-roadmap))
There is no release date planned at the moment.

**Comment by nicodemuz** [comment]
@psyycker Thanks! I noticed that master branch had some doc updates regarding version 0.8.0. Did you close the ticket because this is already implemented?
