### ISSUE TITLE
changeLocale() not changing the locale once called

### ISSUE THREAD

**Issue by MadalinMocanita** [psyycker/react-translation#8]
Hey.  Nice lib, all good but when changing the language, got some issues.

`changeLocale(newLocale)` nor `setLocale(newLocale)` not changing the locale param, which I'm taking from:
`const [locale, setLocale] = useLocale();`

The `setLocale('fr_FR')` call for example won't work eighter, but would throw a _Type 'string' has no call signatures_ error. 
Haven't checked if `setLocale()` function still able to change the locale, but not getting any errors when importing:
`import { Translation, registerTranslations, useTranslation, useLocale, changeLocale } from '@psyycker/react-translation';`
 
Would appreciate any help :)
Ta

**Comment by psyycker** [comment]
Hi @MadalinMocanita 

very sorry for the extremely late reply. I'm however coming with good news as, as part of the version `0.7.0` (just released this morning) the issue is fixed!
I also did some optimization work on the locale management and believe it should improve the workflow but also testability.
Let me know if you're having any other issue and I'll do my best to fix it in the best delay (and faster than 2 months)
